import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './components/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const navLinks = [
    {
      name: 'Home',
      href: '/'
    },
    {
      name: 'Dashboard',
      href: '/dashboard'
    }
  ]
  return (
    <html lang="en">
      <body>
        <Navigation navLink={navLinks}/>
        {children}
      </body>
    </html>
  )
}
